[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_1 = "A5SQJSj9H1nsuWgs2nRNjpkCsLTMzpMhqDGrVoJhi9pq"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vanisama/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
