[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
day_3 = "4YP3z3EGEUakijwxJTd2P912PxaAxGFTWJsd9zjbPgcm"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/vanisama/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
